name: Matrix
on: 
    push:
        branches:
            - main
jobs:
    build:
        strategy:
          matrix:
            node-version: [12, 14, 16]
            operating-system: [ubuntu-latest, windows-latest]  # ubuntu-latest will run again 3 node versions at the same time windows-latest will also run against 3 node versions. in total 6 jobs will run in parallel
        runs-on: ubuntu-latest
        steps:
            - name: Get the code
              uses: actions/checkout@v3
            - name: Install nodejs
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install dependencies
              run: npm ci
            - name: Build the app
              run: npm run build
            - name: Output information
              run: echo "${{ toJson(github) }}"
